// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SYSGES_MAGs.Data;

#nullable disable

namespace SYSGES_MAGs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260406064930_AddDescriptionToTypeMags")]
    partial class AddDescriptionToTypeMags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SYSGES_MAGs.Models.BkPrdCli", b =>
                {
                    b.Property<string>("age")
                        .HasColumnType("text");

                    b.Property<string>("agef")
                        .HasColumnType("text");

                    b.Property<string>("atrf")
                        .HasColumnType("text");

                    b.Property<string>("cli")
                        .HasColumnType("text");

                    b.Property<string>("cnet")
                        .HasColumnType("text");

                    b.Property<string>("cpack")
                        .HasColumnType("text");

                    b.Property<string>("cpro")
                        .HasColumnType("text");

                    b.Property<string>("cqtef")
                        .HasColumnType("text");

                    b.Property<string>("ctar")
                        .HasColumnType("text");

                    b.Property<string>("ctax")
                        .HasColumnType("text");

                    b.Property<string>("ctr")
                        .HasColumnType("text");

                    b.Property<string>("dctar")
                        .HasColumnType("text");

                    b.Property<string>("dde")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ddsou")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("dev")
                        .HasColumnType("text");

                    b.Property<string>("devf")
                        .HasColumnType("text");

                    b.Property<string>("devmep")
                        .HasColumnType("text");

                    b.Property<string>("dex")
                        .HasColumnType("text");

                    b.Property<DateTime?>("dfsou")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("dme")
                        .HasColumnType("text");

                    b.Property<DateTime?>("dmo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("dou")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("dpe")
                        .HasColumnType("text");

                    b.Property<string>("eta")
                        .HasColumnType("text");

                    b.Property<string>("eve")
                        .HasColumnType("text");

                    b.Property<string>("fmep")
                        .HasColumnType("text");

                    b.Property<string>("jour")
                        .HasColumnType("text");

                    b.Property<string>("menc")
                        .HasColumnType("text");

                    b.Property<string>("mhtmep")
                        .HasColumnType("text");

                    b.Property<string>("modu")
                        .HasColumnType("text");

                    b.Property<string>("nanti")
                        .HasColumnType("text");

                    b.Property<string>("nbe")
                        .HasColumnType("text");

                    b.Property<string>("ncp")
                        .HasColumnType("text");

                    b.Property<string>("ncpf")
                        .HasColumnType("text");

                    b.Property<string>("ndos")
                        .HasColumnType("text");

                    b.Property<string>("obs")
                        .HasColumnType("text");

                    b.Property<string>("qte")
                        .HasColumnType("text");

                    b.Property<string>("recfac")
                        .HasColumnType("text");

                    b.Property<string>("rsou")
                        .HasColumnType("text");

                    b.Property<string>("rsou_pack")
                        .HasColumnType("text");

                    b.Property<string>("suf")
                        .HasColumnType("text");

                    b.Property<string>("suff")
                        .HasColumnType("text");

                    b.Property<string>("tdos")
                        .HasColumnType("text");

                    b.Property<string>("ttar")
                        .HasColumnType("text");

                    b.Property<string>("uti")
                        .HasColumnType("text");

                    b.Property<string>("utsou")
                        .HasColumnType("text");

                    b.ToTable("bkprdcli", (string)null);
                });

            modelBuilder.Entity("SYSGES_MAGs.Models.Bkmvti", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Carte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CleBeneficiaire")
                        .HasColumnType("integer");

                    b.Property<string>("CodeAgence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeCarte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeDevise")
                        .HasColumnType("text");

                    b.Property<string>("CodeEmetteur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeIN")
                        .HasColumnType("text");

                    b.Property<string>("CodeOperation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeTarif")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreationCarte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatePrelevement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateValiditeCarte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EstActif")
                        .HasColumnType("text");

                    b.Property<string>("IndicateurDomiciliation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LibelleCarte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroCompte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrixUnitCarte")
                        .HasColumnType("integer");

                    b.Property<int>("ReferenceBeneficiaire")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenceOperation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("TypeBeneficiaire")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TypeMag")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("endPeriod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("startPeriod")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Bkmvtis");
                });

            modelBuilder.Entity("SYSGES_MAGs.Models.Profil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypeProfile")
                        .HasColumnType("integer");

                    b.Property<string>("Userag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("SYSGES_MAGs.Models.TypeMag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PeriodeDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodeFin")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TypeMags");
                });

            modelBuilder.Entity("SYSGES_MAGs.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
